#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

export ORIG_PATH="$PATH"

libexec_path="$(abs_dirname "$0")"
export _P_ROOT="$(abs_dirname "$libexec_path")"
export _P_SHARE="$_P_ROOT/share"

shopt -s nullglob

bin_path=$libexec_path
for plugin_bin in "${_P_ROOT}/plugins/"*/libexec; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec p-help
  ;;
* )
  command_path="$(command -v "p-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "p: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
