#!/usr/bin/env bash
# Usage: p source
# Summary: Output source of p command <command>
# Help: Just run p source <command>, where <command> is the name of the
# desired p command.

if [ "$1" = "--complete" ]; then
  exec p commands
fi

if [ -z "$1" ]; then
  echo "Please provide a command name" >&2
  exit 1
fi

bin="p-$1"
path="$(which $bin)"

if [ -n "$path" ]; then
  exec cat $path
else
  echo "Could not find command $1" >&2
  exit 1
fi
